{
  "format" : "11.1.14",
  "id" : "16D29C451A0AF7D5",
  "config" : {
    "data" : "com.axonivy.connectivity.soap.service.ExceptionData"
  },
  "elements" : [ {
      "id" : "f0",
      "type" : "RequestStart",
      "name" : "interceptException.ivp",
      "config" : {
        "callSignature" : "interceptException",
        "startCategory" : "soap",
        "outLink" : "interceptException.ivp",
        "startCustomFields" : [
          { "name" : "cssIcon", "value" : "fa fa-exclamation-triangle" }
        ],
        "startName" : "9.4 Intercept webservice response"
      },
      "visual" : {
        "at" : { "x" : 96, "y" : 64 },
        "labelOffset" : { "x" : 20, "y" : 39 }
      },
      "connect" : [
        { "id" : "f3", "to" : "f2" }
      ]
    }, {
      "id" : "f1",
      "type" : "TaskEnd",
      "visual" : {
        "at" : { "x" : 352, "y" : 64 }
      }
    }, {
      "id" : "f2",
      "type" : "WebServiceCall",
      "config" : {
        "clientId" : "16D2A643A3A25C52",
        "port" : "ServiceWithExceptionPort",
        "inputParams" : {
          "parameters.exceptionMessage" : "\"This exception has been intercepted\"",
          "parameters.throwException" : "true"
        },
        "operation" : "call",
        "properties" : {
          "AXIS.mapNullValues" : "true",
          "AXIS2.autoInitFirstLevelFields" : "true",
          "org.apache.cxf.transport.process_fault_on_http_400" : "true"
        }
      },
      "visual" : {
        "at" : { "x" : 224, "y" : 64 }
      },
      "connect" : [
        { "id" : "f4", "to" : "f1" }
      ]
    }, {
      "id" : "f5",
      "type" : "ProcessAnnotation",
      "name" : [
        "This Web Service Call Activity is being intercepted by an OutFaultInterceptor",
        "have a look at the service: Processes > soap > service > serviceWithException"
      ],
      "visual" : {
        "at" : { "x" : 336, "y" : 144 },
        "size" : { "width" : 512, "height" : 44 }
      },
      "connect" : [
        { "id" : "f6", "to" : "f2" }
      ]
    } ]
}